<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [478]:
# Import statements
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
import random

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

correct_outputs = [[1], [1], [1], [0]]
# correct_outputs = [[value] for value in data['y']]

df = pd.DataFrame.from_dict(data).astype('int')

df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [479]:
X = df[['x1', 'x2']]
X['bias'] = [1,1,1,1] # Simulated bias
y = df['y']

X.head()

x1  x2  bias
0   0   0     1
1   1   0     1
2   0   1     1
3   1   1     1

In [480]:
inputs = X[['x1', 'x2', 'bias']].values

inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]], dtype=int64)

In [481]:
# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

### Initialize random weights

In [490]:
weights = 2 * np.random.random((3,1)) - 1

weights

array([[-0.08786003],
       [ 0.57035192],
       [-0.60065244]])

### Calculate weighted sum of inputs and weights

In [491]:
weighted_sum = np.dot(inputs, weights)

weighted_sum

array([[-0.60065244],
       [-0.68851247],
       [-0.03030051],
       [-0.11816054]])

### Training first epoch

In [492]:
activated_output = sigmoid(weighted_sum) # Prediction first epoch

activated_output

array([[0.35419444],
       [0.33436406],
       [0.49242545],
       [0.47049419]])

### Calculate error

In [493]:
error = correct_outputs - activated_output # Absolute error

error

array([[ 0.64580556],
       [ 0.66563594],
       [ 0.50757455],
       [-0.47049419]])

### Gradient descent (weights correction)

In [536]:
adjustments = error * sigmoid_derivative(weighted_sum)

adjustments

array([[ 3.00437454e-11],
       [ 2.63639887e-04],
       [ 2.63639887e-04],
       [-3.69145890e-04]])

In [495]:
# weights = 0 # Clear

weights += np.dot(inputs.T, adjustments)

weights

array([[-0.05692688],
       [ 0.5800025 ],
       [-0.29513273]])

### Update weights 'n' times

In [496]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calculate absolute error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-8.01857795]
 [-8.01857795]
 [12.11433322]]
Output after training
[[0.99999452]
 [0.98362844]
 [0.98362844]
 [0.01940232]]


### Accuracy Score

In [497]:
def binary_classifier(result):
    if result >= 0.5:
        return 1
    else:
        return 0
    
binary_activated_output = pd.DataFrame(activated_output)[0].apply(binary_classifier)

binary_activated_output

0    1
1    1
2    1
3    0
Name: 0, dtype: int64

In [498]:
print('Accuracy Score:', accuracy_score(df['y'], binary_activated_output))

Accuracy Score: 1.0


### NAND Gate Prediction

In [551]:
# Danke Brian!
np.random.seed(42)

obs = 1000
choices = [1, 0]

def nand(val1, val2):
     return 0 if (val1 == 1) & (val2 == 1) else 1
    
x1 = [random.choice(choices) for i in range(0,obs)]
x2 = [random.choice(choices) for i in range(0,obs)]
y = []

for i in range(0, obs): 
    y_true = nand(x1[i], x2[i])
    y.append(y_true)

df_nand = pd.DataFrame({'x1': x1, 'x2': x2, 'y':y})

df_nand['bias'] = 1 
# df_nand['bias'] = np.ones((obs,), dtype=int)

df_nand

x1  x2  y  bias
0     0   1  1     1
1     0   1  1     1
2     1   0  1     1
3     0   0  1     1
4     0   1  1     1
..   ..  .. ..   ...
995   0   1  1     1
996   0   0  1     1
997   0   0  1     1
998   0   1  1     1
999   0   1  1     1

[1000 rows x 4 columns]

In [552]:
df_nand['y'].value_counts()

1    737
0    263
Name: y, dtype: int64

In [557]:
# inputs_nand = df_nand[['x1', 'x2', 'bias']].values
inputs_nand = df_nand[['x1', 'x2', 'bias']].values

inputs_nand

array([[0, 1, 1],
       [0, 1, 1],
       [1, 0, 1],
       ...,
       [0, 0, 1],
       [0, 1, 1],
       [0, 1, 1]], dtype=int64)

In [558]:
correct_outputs_nand = [[value] for value in df_nand['y']]

# correct_outputs_nand

[[1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [0],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [0],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [0],
 [0],
 [0],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [0],
 [0],
 [1],
 [1],
 [0],
 [0],
 [1],
 [1],
 [0],
 [1],
 [0],
 [1],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [0],
 [1],
 [0],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1]

In [573]:
weights_nand = 2 * np.random.random((3,1)) - 1

weights_nand

array([[-0.93122296],
       [ 0.8186408 ],
       [-0.48244004]])

In [574]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum_nand = np.dot(inputs_nand, weights_nand)
    
    # Activate!
    activated_output_nand = sigmoid(weighted_sum_nand)
    
    # Calculate absolute error
    error_nand = correct_outputs_nand - activated_output_nand
    
    adjustments_nand = error_nand * sigmoid_derivative(weighted_sum_nand)
    
    # Update the Weights
    weights_nand += np.dot(inputs_nand.T, adjustments_nand)
    
print("Weights after training")
# print(weights_nand)

print("Output after training")
# print(activated_output_nand)

Weights after training
Output after training


### Testing result accuracy

In [575]:
binary_activated_output_nand = pd.DataFrame(activated_output_nand)[0].apply(binary_classifier)

binary_activated_output_nand

0      1
1      1
2      1
3      1
4      1
      ..
995    1
996    1
997    1
998    1
999    1
Name: 0, Length: 1000, dtype: int64

In [576]:
print('Accuracy Score:', accuracy_score(df_nand['y'], binary_activated_output_nand))

Accuracy Score: 0.737


In [577]:
df_comparison_nand = pd.DataFrame({'control': df_nand['y'], 'result': binary_activated_output_nand})

In [578]:
print(df_comparison_nand['result'].value_counts()) # Binary sanity test
df_comparison_nand

1    1000
Name: result, dtype: int64


control  result
0          1       1
1          1       1
2          1       1
3          1       1
4          1       1
..       ...     ...
995        1       1
996        1       1
997        1       1
998        1       1
999        1       1

[1000 rows x 2 columns]

### Using Perceptron class on NAND gate

In [ ]:
class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

        # Randomly Initialize Weights
        weights = ...

        for i in range(self.niter):
            # Weighted sum of inputs / weights

            # Activate!

            # Cac error

            # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [441]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [449]:
diabetes['Bias'] = 1

diabetes

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  Bias  
0                       0.627   50        1     1  
1                       0.351   31        0     1  
2                       0.672   32        1     1  
3                       0.167   21        0     1  
4                       2.288   33        1     1  
..                        ...  ...      ...   ...  
763                     0.171   63        0     1  
764                     0.340   27        0     1  
765                     0.245   30        0     1  
766                     0.349   47        1     1  
767                     0.315   23        0     1  

[768 rows x 10 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [456]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

# feats = list(diabetes)[:-1]
feats = list(diabetes.drop(columns='Outcome'))

feats

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age',
 'Bias']

In [461]:
X_normal = Normalizer().fit_transform(diabetes[feats])
X_scaler = MinMaxScaler().fit_transform(diabetes[feats])

In [462]:
X_normal

array([[0.03355185, 0.82761219, 0.40262215, ..., 0.00350617, 0.27959871,
        0.00559197],
       [0.00842371, 0.71601493, 0.55596454, ..., 0.00295672, 0.26113486,
        0.00842371],
       [0.04039717, 0.9240852 , 0.32317734, ..., 0.00339336, 0.16158867,
        0.00504965],
       ...,
       [0.026915  , 0.65134299, 0.38757599, ..., 0.00131883, 0.16149   ,
        0.005383  ],
       [0.00665291, 0.83826692, 0.39917472, ..., 0.00232187, 0.31268687,
        0.00665291],
       [0.00791429, 0.73602906, 0.55400037, ..., 0.002493  , 0.18202869,
        0.00791429]])

In [463]:
X_scaler

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.23441503, 0.48333333,
        0.        ],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.11656704, 0.16666667,
        0.        ],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.25362938, 0.18333333,
        0.        ],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.07130658, 0.15      ,
        0.        ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.11571307, 0.43333333,
        0.        ],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.10119556, 0.03333333,
        0.        ]])

In [ ]:
y

In [439]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

        # Randomly Initialize Weights
        weights = ...

        for i in range(self.niter):
            # Weighted sum of inputs / weights

            # Activate!

            # Cac error

            # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

IndentationError: expected an indented block (<ipython-input-439-076543c6f8b3>, line 18)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?