<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:** Neurons receive inputs, passing their signal (if activated) to the next layer if a certain threshold is reached and 
- **Input Layer:** The input layer is made of your data. This is how your data begins to go through the network.
- **Hidden Layer:** The hidden layer can be made up of multiple layers and is where most of the variation in architecture of an NN occurs. 
- **Output Layer:** The output is the prediction or classification that is given by your neural network.
- **Activation:** A neuron is activated according to one of many activation functions, such as tanh, relu, sigmoid, or linear. This would cause the neuron to send a signal on to the next neuron.
- **Backpropagation:** The neural network operates according to a loss function and it wants to minimize the loss, therefore it will keep iterating through the layers, according to a gradient. 


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [2]:
import pandas as pd
import numpy as np

candy = pd.read_csv('chocolate_gummy_bears.csv')

In [3]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. You will not be able to achieve more than ~50% with the simple perceptron. Explain why you could not achieve a higher accuracy with the *simple perceptron* architecture, because it's possible to achieve ~95% accuracy on this dataset. Provide your answer in markdown (and *optional* data anlysis code) after your perceptron implementation. 

In [4]:
# Start your candy perceptron here

X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values

In [5]:
candy.ate.value_counts()

1    5000
0    5000
Name: ate, dtype: int64

In [6]:
class Perceptron(object):
  def __init__(self, rate = 0.01, niter = 10):
    self.rate = rate
    self.niter = niter

  def fit(self, X, y):

    # weights
    self.weight = np.zeros(1 + X.shape[1])

    # Number of misclassifications
    self.errors = []  # Number of misclassifications

    for i in range(self.niter):
      err = 0
      for xi, target in zip(X, y):
        delta_w = self.rate * (target - self.predict(xi))
        self.weight[1:] += delta_w * xi
        self.weight[0] += delta_w
        err += int(delta_w != 0.0)
      self.errors.append(err)
    return self
    
    for i in range(self.niter):
        weighted_sum = np.dot(X, self.weight)
        activated_output = sigmoid(weighted_sum)
        error = correct_outputs - activated_output
        adjustments = error*sigmoid_derivative(activated_output)
        weights =+ np.dot(X.T, adjustments)
        return weights
  def net_input(self, X):
    """Calculate net input"""
    return np.dot(X, self.weight[1:]) + self.weight[0]

  def predict(self, X):
    """Return class label after unit step"""
    return np.where(self.net_input(X) >= 0.0, 1, 0)

In [7]:
from sklearn.metrics import accuracy_score

per = Perceptron(niter=10)
per.fit(X,y)
y_pred = per.predict(X)

accuracy_score(y_pred, y)

0.5

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [8]:
y = y.reshape(-1,1)

X.shape, y.shape

((10000, 2), (10000, 1))

In [9]:
class NeuralNetwork():
    def __init__(self, input_size = 2, hiddenNodes = 4, outputNodes = 1):
#     def __init__(self, input_size, hiddenNodes, outputNodes):
        # Set up Architecture of neural network
        self.input = input_size 
        self.hiddenNodes = hiddenNodes
        self.outputNodes = outputNodes
        
        # Initial Weights
        # 2x3 matrix for first layer
        self.weights1 = np.random.randn(self.input, self.hiddenNodes)
        #3x1 matrix for hidden to output layer
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):

        #weighted sum of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        #add bias
#         self.hidden_sum + bias

        #Activations of weighted sums
        self.activated_hidden = self.sigmoid(self.hidden_sum)

        #Weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)

        # Final Activation of output
        self.activated_output = self.sigmoid(self.output_sum)


        return self.activated_output
    
    def get_attributes(self):
        
        attributes = ['weights1', 'hidden_sum', 'activated_hidden', 'weights2', 'output']

        [print(i + '\n', getattr(nn,i), '\n' + '---'*3) for i in dir(nn) if i in attributes]

    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)

        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [10]:
nn = NeuralNetwork()

# Number of Epochs / Iterations
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.21828036]
 [0.26820486]
 [0.21828036]
 ...
 [0.21828036]
 [0.21828036]
 [0.26820486]]
Loss: 
 0.3157467070147821
+---------EPOCH 2---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.50037399]
 [0.50011314]
 [0.50037399]
 ...
 [0.50037399]
 [0.50037399]
 [0.50011314]]
Loss: 
 0.42464145539295123
+---------EPOCH 3---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.5005672 ]
 [0.50012835]
 [0.5005672 ]
 ...
 [0.5005672 ]
 [0.5005672 ]
 [0.50012835]]
Loss: 
 0.4245950477112503
+---------EPOCH 4---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.5010664 ]
 [

P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [88]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from keras.optimizers import SGD
from keras.models import Sequential 
from keras.layers import Dense, Dropout
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
167   62    0   0       140   268    0        0      160      0      3.6   
301   57    1   0       130   131    0        1      115      1      1.2   
9     57    1   2       150   168    0        1      174      0      1.6   
0     63    1   3       145   233    1        0      150      0      2.3   
16    58    0   2       120   340    0        1      172      0      0.0   

     slope  ca  thal  target  
167      0   2     2       0  
301      1   1     3       0  
9        2   0     2       1  
0        0   0     1       1  
16       2   0     2       1

In [89]:
target = 'target'
features = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal']

X = df[features]
y = df[target]

In [90]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns.tolist())

In [91]:
## BASELINE ACCURACY

#Identify target in our df and set the predicted value to the mode
y_true = df['target']
majority = df['target'].mode()[0]

#Create a list of predictions for the length of our df
y_pred = [majority] * len(y_true)

#Use accuracy_score to check our baseline accuracy
from sklearn.metrics import accuracy_score
print("Baseline Accuracy:", accuracy_score(y_true, y_pred))

Baseline Accuracy: 0.5445544554455446


In [92]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X_scaled, 
    y,
    test_size=0.3,
    random_state=5
    )

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((212, 13), (91, 13), (212,), (91,))

In [93]:
batch_size = 20
num_classes = 2
epochs = 10

opt = SGD(lr=0.1, momentum=0.9)

model = Sequential()
model.add(Dense(5, activation='relu', input_shape=(13,)))
model.add(Dense(1, activation='sigmoid'))
model.compile(
    loss='binary_crossentropy', 
    optimizer=opt, 
    metrics=['accuracy']
    )

history = model.fit(
    x_train, 
    y_train, 
    validation_data=(x_test, y_test), 
    epochs=epochs,
    batch_size=batch_size,
    verbose=True
    )

Train on 212 samples, validate on 91 samples
Epoch 1/10
212/212 [==============================] - 3s 14ms/step - loss: 0.5932 - accuracy: 0.7028 - val_loss: 0.4257 - val_accuracy: 0.8681
Epoch 2/10
212/212 [==============================] - 0s 785us/step - loss: 0.4477 - accuracy: 0.8113 - val_loss: 0.3474 - val_accuracy: 0.8791
Epoch 3/10
212/212 [==============================] - 0s 911us/step - loss: 0.4299 - accuracy: 0.8302 - val_loss: 0.3532 - val_accuracy: 0.8681
Epoch 4/10
212/212 [==============================] - 0s 527us/step - loss: 0.4035 - accuracy: 0.8538 - val_loss: 0.3533 - val_accuracy: 0.8681
Epoch 5/10
212/212 [==============================] - 0s 516us/step - loss: 0.3620 - accuracy: 0.8302 - val_loss: 0.3539 - val_accuracy: 0.8681
Epoch 6/10
212/212 [==============================] - 0s 510us/step - loss: 0.3330 - accuracy: 0.8396 - val_loss: 0.3590 - val_accuracy: 0.8681
Epoch 7/10
212/212 [==============================] - 0s 481us/step - loss: 0.3243 - accurac

In [94]:
def create_model(momentum=0, lr=0, dropout_rate=0, kernel_initializer='normal'):
    opt = SGD(lr=lr, momentum=momentum)
    model = Sequential()
    model.add(Dense(30, 
                    input_shape=(13,),
                    kernel_initializer=kernel_initializer,
                    activation='sigmoid'
                    ))
    model.add(Dropout(dropout_rate))
    model.add(Dense(20, activation='relu'))
    model.add(Dense(3, activation='relu'))
    model.add(Dense(1, kernel_initializer=kernel_initializer, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

# define the grid search parameters
momentum = [0.3, 0.4]
lr = [0.001, 0.01, 0.1, 0.2, 0.3, 0.4, 0.5]
dropout_rate = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
batch_size = [5, 10, 50, 100]
epochs = [10]

param_grid = dict(batch_size=batch_size, epochs=epochs)

In [95]:
# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(x_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.5571428656578064 using {'batch_size': 5, 'epochs': 10}
Means: 0.5571428656578064, Stdev: 0.06179203482097474 with: {'batch_size': 5, 'epochs': 10}
Means: 0.44772979617118835, Stdev: 0.06596504404181693 with: {'batch_size': 10, 'epochs': 10}
Means: 0.4810631275177002, Stdev: 0.06052877453845564 with: {'batch_size': 50, 'epochs': 10}
Means: 0.495348846912384, Stdev: 0.08403528686128361 with: {'batch_size': 100, 'epochs': 10}


In [96]:
param_grid = dict(lr=lr, epochs=[10], batch_size=[10])

In [97]:
# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(x_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.7919158339500427 using {'batch_size': 10, 'epochs': 10, 'lr': 0.4}
Means: 0.495348846912384, Stdev: 0.08403528686128361 with: {'batch_size': 10, 'epochs': 10, 'lr': 0.001}
Means: 0.5524917006492615, Stdev: 0.06578893543637097 with: {'batch_size': 10, 'epochs': 10, 'lr': 0.01}
Means: 0.5810631275177002, Stdev: 0.07716547119620129 with: {'batch_size': 10, 'epochs': 10, 'lr': 0.1}
Means: 0.7347729802131653, Stdev: 0.13190664894583184 with: {'batch_size': 10, 'epochs': 10, 'lr': 0.2}
Means: 0.7408637881278992, Stdev: 0.1428807570360425 with: {'batch_size': 10, 'epochs': 10, 'lr': 0.3}
Means: 0.7919158339500427, Stdev: 0.06406055429385626 with: {'batch_size': 10, 'epochs': 10, 'lr': 0.4}
Means: 0.7822812795639038, Stdev: 0.08145326126683324 with: {'batch_size': 10, 'epochs': 10, 'lr': 0.5}


In [98]:
param_grid = dict(dropout_rate=dropout_rate, lr=[0.2], epochs=[10], batch_size=[10])

In [99]:
# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(x_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.7965669870376587 using {'batch_size': 10, 'dropout_rate': 0.1, 'epochs': 10, 'lr': 0.2}
Means: 0.7637873649597168, Stdev: 0.044172860457633925 with: {'batch_size': 10, 'dropout_rate': 0.0, 'epochs': 10, 'lr': 0.2}
Means: 0.7965669870376587, Stdev: 0.06440253004626151 with: {'batch_size': 10, 'dropout_rate': 0.1, 'epochs': 10, 'lr': 0.2}
Means: 0.7306755304336547, Stdev: 0.0729323220852061 with: {'batch_size': 10, 'dropout_rate': 0.2, 'epochs': 10, 'lr': 0.2}
Means: 0.6796234846115112, Stdev: 0.11204745853411106 with: {'batch_size': 10, 'dropout_rate': 0.3, 'epochs': 10, 'lr': 0.2}
Means: 0.6648947954177856, Stdev: 0.15101867102983685 with: {'batch_size': 10, 'dropout_rate': 0.4, 'epochs': 10, 'lr': 0.2}
Means: 0.6239202737808227, Stdev: 0.126003933885156 with: {'batch_size': 10, 'dropout_rate': 0.5, 'epochs': 10, 'lr': 0.2}


In [ ]:
param_grid = dict(momentum=momentum, dropout_rate=[0.1], lr=[0.2], epochs=[10], batch_size=[10])

In [104]:
# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(x_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.8106312274932861 using {'batch_size': 10, 'dropout_rate': 0.1, 'epochs': 10, 'lr': 0.2, 'momentum': 0.4}
Means: 0.7772979021072388, Stdev: 0.09479823377517681 with: {'batch_size': 10, 'dropout_rate': 0.1, 'epochs': 10, 'lr': 0.2, 'momentum': 0.3}
Means: 0.8106312274932861, Stdev: 0.06154803689407415 with: {'batch_size': 10, 'dropout_rate': 0.1, 'epochs': 10, 'lr': 0.2, 'momentum': 0.4}


In [105]:
opt = SGD(lr=0.2, momentum=0.4)
model = Sequential()
model.add(Dense(30, input_shape=(13,), kernel_initializer='normal', activation='sigmoid'))
model.add(Dropout(0.1))
model.add(Dense(20, activation='relu'))
model.add(Dense(3, activation='relu'))
model.add(Dense(1, kernel_initializer='normal', activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])

In [106]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), verbose=True, epochs=10, batch_size=10)

Train on 212 samples, validate on 91 samples
Epoch 1/10
212/212 [==============================] - 6s 27ms/step - loss: 0.6945 - accuracy: 0.5283 - val_loss: 0.6934 - val_accuracy: 0.5275
Epoch 2/10
212/212 [==============================] - 0s 1ms/step - loss: 0.6810 - accuracy: 0.5566 - val_loss: 0.6451 - val_accuracy: 0.7363
Epoch 3/10
212/212 [==============================] - 0s 2ms/step - loss: 0.5823 - accuracy: 0.7311 - val_loss: 0.7198 - val_accuracy: 0.5824
Epoch 4/10
212/212 [==============================] - 0s 1ms/step - loss: 0.5503 - accuracy: 0.7594 - val_loss: 0.4047 - val_accuracy: 0.8791
Epoch 5/10
212/212 [==============================] - 0s 1ms/step - loss: 0.4810 - accuracy: 0.7736 - val_loss: 0.4327 - val_accuracy: 0.7912
Epoch 6/10
212/212 [==============================] - 0s 1ms/step - loss: 0.4854 - accuracy: 0.7783 - val_loss: 0.4346 - val_accuracy: 0.8681
Epoch 7/10
212/212 [==============================] - 0s 1ms/step - loss: 0.4597 - accuracy: 0.7925 - 

In [107]:
model.summary()

Model: "sequential_308"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1209 (Dense)           (None, 30)                420       
_________________________________________________________________
dropout_291 (Dropout)        (None, 30)                0         
_________________________________________________________________
dense_1210 (Dense)           (None, 20)                620       
_________________________________________________________________
dense_1211 (Dense)           (None, 3)                 63        
_________________________________________________________________
dense_1212 (Dense)           (None, 1)                 4         
Total params: 1,107
Trainable params: 1,107
Non-trainable params: 0
_________________________________________________________________


In [108]:
score = model.evaluate(x_test, y_test, verbose=0)

In [109]:
print('Model Accuracy = ',score[1])

Model Accuracy =  0.8131868243217468
