<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. This multi-layer one shouldn't have any such problems.

In [1]:
# imports 
import numpy as np
import pandas as pd 

In [4]:
# features
features = np.array((
                    [0,0,1],
                    [0,1,1],
                    [1,0,1],
                    [0,1,0],
                    [1,0,0],
                    [1,1,1],
                    [0,0,0]), dtype=float)

# target
target = np.array(([0],[1],[1],[1],[1],[0],[0]), dtype=float)

In [6]:
##### Your Code Here #####

class NeuralNetwork:
    
    def __init__(self):
        # inputs, hidden, output per spec above
        self.inputs = 3
        self.hiddenNodes = 4
        self.outputNodes = 1
        
        # initialize weights for input -> hidden which is 3 x 4 array
        self.weights_one = np.random.randn(self.inputs, self.hiddenNodes)
        # initialize weights for hidden -> output which is 4 x 1 array
        self.weights_two = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    # sigmoid function 
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    # derivative of sigmoid helper
    def derivative(self, s):
        sx = self.sigmoid(s)
        return sx * (1-sx)
    
    def feed_forward(self, X):
        """
        Calculate NN inference using feed forward
        """
        # weighted sum
        self.hidden_sum = np.dot(X, self.weights_one)
        
        # activate
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # weighted sum of activated hidden which output will use
        self.output_sum = np.dot(self.activated_hidden, self.weights_two)
        
        # final activation of output (predictions)
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        """
        Back prop thru with errors and make adjustments
        """
        # absolute error
        self.o_error = y - o
        # partial derivative of error 
        self.o_delta = self.o_error * self.derivative(o)
        # z2 error: amount output layer weights were off by 
        self.z2_error = self.o_delta.dot(self.weights_two.T)
        
        # z2 delta
        self.z2_delta = self.z2_error*self.derivative(self.activated_hidden)
        
        # adjust weights by the deltas
        self.weights_one += X.T.dot(self.z2_delta)
        self.weights_two += self.activated_hidden.T.dot(self.o_delta)
    
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)
        

In [7]:
nn = NeuralNetwork()

nn.train(features, target)

In [ ]:
nn.o_error, nn.o_delta, nn.z2_error, nn.z2_delta # one iteration's numbers


In [14]:
for i in range(10000):
    if ((i+1) % 1000 == 0):
        print('Input: \n', features)
        print('Output: \n', target)
        print('Predicted Output \n', str(nn.feed_forward(features)))
        print("Loss: \n", str(np.mean(np.square(target - nn.feed_forward(features)))))
    
    nn.train(features, target)

Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output 
 [[2.23629222e-11]
 [9.98199280e-01]
 [9.98209429e-01]
 [9.98199817e-01]
 [9.98210003e-01]
 [2.99328321e-03]
 [2.23353872e-03]]
Loss: 
 3.834560547251185e-06
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output 
 [[1.87150951e-11]
 [9.98277587e-01]
 [9.98287195e-01]
 [9.98278089e-01]
 [9.98287731e-01]
 [2.86311268e-03]
 [2.13609121e-03]]
Loss: 
 3.508221845296566e-06
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output 
 [[1.57818702e-11]
 [9.98349365e-01]
 [9.98358483e-01]
 [9.98349836e-01]
 [9.98358985e-01]
 [2.74379710e-03]
 [2.04678731e-03]]
Loss: 
 3.221843980158908e-06
Input: 
 [[0. 0. 1.]
 [0. 1. 1.

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [39]:
# we are just categorizing 0 or not 0 since we do not know 'softmax'

import numpy as np
from tensorflow.keras.datasets import mnist # like the iris of neural networks
# mnist is some hand written digits
from tensorflow.keras.utils import to_categorical

In [2]:
# input image dimensions
img_rows, img_cols = 28, 28

In [31]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [32]:
# reshape into 1 x 784 instead of 28 x 28 because of formatting limits
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [16]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [33]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [40]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

In [ ]:
##### Your Code Here #####



## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?