<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [36]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import Normalizer

In [37]:
np.random.seed(42)

X = np.array([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [0,1,0],
    [1,0,0],
    [1,1,1],
    [0,0,0]
])

y = np.array(([0], [1], [1], [1], [1], [0], [0]))

In [38]:
class NNet:
    def __init__(self):
        self.inputs = 3
        
        # Hidden Nodes is arbitrary Number
        self.hiddenNodes = 4
        
        # Only one output node b/c only trying to predict one thing
        self.outputNodes = 1
        
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def feed_forward(self, X):
        """Calculate the NNet inference using the feed forward, aka predict """
        
        # Combining  inputs and weights in a weighted sum
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Applying sigmoid to weighted sums
        # Activated Values
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Apply activation function to the weighted sums
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
        

In [39]:
# Initialize Weights

nn = NNet()

print("Layer 1 wieghts: \n", nn.weights1)
print(f"The shape of the layer 1 weights are {nn.weights1.shape}")
print("Layer 2 wieghts: \n", nn.weights2)
print(f"The shape of the layer 2 weights are {nn.weights2.shape}")

Layer 1 wieghts: 
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]
The shape of the layer 1 weights are (3, 4)
Layer 2 wieghts: 
 [[0.83244264]
 [0.21233911]
 [0.18182497]
 [0.18340451]]
The shape of the layer 2 weights are (4, 1)


In [40]:
# Try to make a prediction with our updated 'net

nn = NNet()
output = nn.feed_forward(X)
print("intput", X)
print("output", output)

intput [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
output [[0.69745783]
 [0.72545584]
 [0.7220714 ]
 [0.70213445]
 [0.69763754]
 [0.74560047]
 [0.67006233]]


In [41]:
# Calculate Error of first result
error = y - output
error

array([[-0.69745783],
       [ 0.27454416],
       [ 0.2779286 ],
       [ 0.29786555],
       [ 0.30236246],
       [-0.74560047],
       [-0.67006233]])

In [42]:
output_all = nn.feed_forward(X)
error_all = y - output_all
print("output_all \n", output_all)
print()
print("error_all \n", error_all)

output_all 
 [[0.69745783]
 [0.72545584]
 [0.7220714 ]
 [0.70213445]
 [0.69763754]
 [0.74560047]
 [0.67006233]]

error_all 
 [[-0.69745783]
 [ 0.27454416]
 [ 0.2779286 ]
 [ 0.29786555]
 [ 0.30236246]
 [-0.74560047]
 [-0.67006233]]


## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [17]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [18]:
# input image dimensions
img_rows, img_cols = 28, 28

In [19]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [20]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [21]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [22]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [23]:
# A Nice Binary target for ya to work with
print(y_train.shape)
y_train

(60000,)


array([0., 1., 0., ..., 0., 0., 0.])

In [24]:
attributes = ['weights1', 'hidden_sum', 'activated_hidden', 'weights2', 'activated_output']
[print(i+'\n', getattr(nn,i), '\n'+'---'*3) for i in attributes if i[:2]!= '__'] 

weights1
 [[0.03559023 0.9943303  0.23272835 0.05383052]
 [0.18987533 0.03895785 0.39181089 0.80240178]
 [0.34124445 0.44418341 0.67558677 0.50889407]] 
---------
hidden_sum
 [[0.34124445 0.44418341 0.67558677 0.50889407]
 [0.53111978 0.48314125 1.06739767 1.31129585]
 [0.37683468 1.43851371 0.90831512 0.56272459]
 [0.18987533 0.03895785 0.39181089 0.80240178]
 [0.03559023 0.9943303  0.23272835 0.05383052]
 [0.56671001 1.47747156 1.30012602 1.36512638]
 [0.         0.         0.         0.        ]] 
---------
activated_hidden
 [[0.58449278 0.6092554  0.662753   0.62454718]
 [0.62974424 0.61848936 0.74410171 0.78772992]
 [0.59310944 0.80822439 0.71265526 0.63708272]
 [0.54732673 0.50973823 0.59671856 0.69048801]
 [0.50889662 0.72994239 0.55792089 0.51345438]
 [0.63800368 0.81419037 0.78585619 0.79659161]
 [0.5        0.5        0.5        0.5       ]] 
---------
weights2
 [[0.86144569]
 [0.86603568]
 [0.0099107 ]
 [0.77804631]] 
---------
activated_output
 [[0.82107396]
 [0.84532424]
 

[None, None, None, None, None]

### Estimating Your `net

In [28]:
##### Your Code Here #####

class NNetbackprop:
    def __init__(self):
        self.inputs = 784
        
        # Hidden Nodes is arbitrary Number
        self.hiddenNodes = 4
        
        # Only one output node b/c only trying to predict one thing
        self.outputNodes = 1
        
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """Calculate the NNet inference using the feed forward, aka predict """
        
        # Combining  inputs and weights in a weighted sum
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Applying sigmoid to weighted sums
        # Activated Values
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Apply activation function to the weighted sums
        self.activated_output = self.sigmoid(self.output_sum)
    
        return self.activated_output
    
    def backward(self, X, y, o):
        """Back Prop through Network"""
        
        self.o_error = y - o
        
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        self.weights1 += X.T.dot(self.z2_delta)
        
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)
        
        

In [31]:
nn = NNetbackprop()
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', x_train)
        print('Actual Output: \n', y_train)
        print('Predicted Output: \n', str(nn.feed_forward(x_train)))
        print("Loss: \n", str(np.mean(np.square(y_train - nn.feed_forward(x_train)))))
    nn.train(x_train,y_train)

+---------EPOCH 1---------+
Input: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Actual Output: 
 [0. 1. 0. ... 0. 0. 0.]
Predicted Output: 
 [[0.93595603]
 [0.93595603]
 [0.93595603]
 ...
 [0.93595603]
 [0.93595603]
 [0.93595603]]
Loss: 
 0.7899414388217032


KeyboardInterrupt: 

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?

In [132]:
x_train.shape

(60000, 784)

In [44]:
data = {
    'x1': [0,0,1,0,1,1,0],
    'x2': [0,1,0,1,0,1,0],
    'x3': [1,1,1,0,0,1,0],
    'y': [0,1,1,1,1,0,0]
}

Xx = np.array(list(data.values()))[:1].T
Xx

array([[0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0]])

In [33]:
data

{'x1': [0, 0, 1, 0, 1, 1, 0],
 'x2': [0, 1, 0, 1, 0, 1, 0],
 'x3': [1, 1, 1, 0, 0, 1, 0],
 'y': [0, 1, 1, 1, 1, 0, 0]}